name: deploy to stratos test

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: npm install
      run: npm i && npm i --only=dev

    - name: npm run build
      run: npm run build


    # Copying files using rsyc
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: build/
        remote_path: ${{ secrets.REMOTE_DIR_TEST }}
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_port: 22
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_key: ${{ secrets.SSH_KEY }}
